### ISSUE TITLE
Regarding ExpressionBinding in ReportHelper.cs

### ISSUE THREAD

**Issue by KevalrChauhan** [DevExpress-Examples/blazor-server-dxdatagrid-export#1]
Hello, Can you please help with below problem.
ReportHelper.cs -> line 54
So I want to generate an expression which replaces TRUE (database column type boolean) with "〇" and FALSE with "✖"
So currently my exported excel would show TRUE & FALSE in cells I want to show "〇" and "✖".
and also there is a column of type "int" so if the value is say 1111 I want to show 11-11.

Thank You.

**Comment by zabelin-vladimir** [comment]
Hello @KevalrChauhan,

As I see, you posted the same question in the following thread in our Support Center: [DxDataGrid for Blazor - How to export filtered data to Excel](https://supportcenter.devexpress.com/ticket/details/t959701/dxdatagrid-for-blazor-how-to-export-filtered-data-to-excel). Let's continue our discussion in that ticket.
